// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejxvhauuxwjqlxadzdee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqeHZoYXV1eHdqcWx4YWR6ZGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzgwNzgsImV4cCI6MjA3MjQ1NDA3OH0.sChH8IWHEgmAactUaJRiJOJVzsCQLNzOFXnuvDimcIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});